sudo: required
language: generic
services: docker
before_install:
- openssl aes-256-cbc -K $encrypted_5b03a0754c69_key -iv $encrypted_5b03a0754c69_iv
  -in .dropbox_uploader.enc -out ~/.dropbox_uploader -d
script:
- docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c "tectonic danmcgrathresume.tex"
- chmod +x ./dropbox_uploader.sh
- ./dropbox_uploader.sh upload danmcgrathresume.pdf danmcgrathresume.pdf
- curl -X POST -d {} $PORTFOLIO_BUILD_HOOK
