name: Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: wtfjoke/setup-tectonic@v3
      - run: tectonic danmcgrathresume.tex
      - uses: actions/upload-artifact@v4
        with:
          name: resume
          path: danmcgrathresume.pdf
